# BaseNode signifies that, upon start, the node will not attempt to connect to
# any other remote nodes. Essentially one node will be spun up and then others
# may attempt to connect to this base node. The default is set to True if the
# config file doesn to load correctly.
# Default: true
BaseNode: true
# Port we listen for incoming connections on.
# Default: 5454
ListenPort: 5454
# A list of nodes which our node will attempt to connect to upon startup.
# Default: 127.0.0.1:5455
RemotePeers:
  - 127.0.0.1:5454
